export async function GET({ params, request }) {
  return new Response(
    `robots.txt generated by www.seoptimer.com
User-agent: *
Disallow:
Sitemap: https://blog.luciancah.com/sitemap-index.xml`,
    {
      headers: {
        "content-type": "text/plain",
      },
    },
  );
}
